"""Fixed-head hydraulic conversion used by the optimizer and validation tools."""

WATER_DENSITY_KG_PER_CUBIC_METRE = 1000.0
GRAVITATIONAL_ACCELERATION_METRES_PER_SECOND_SQUARED = 9.81
FIXED_HYDRAULIC_HEAD_METRES = 146.78899082568807
CUBIC_METRES_PER_FLOW_UNIT = 1000.0
SECONDS_PER_HOUR = 3600.0
WATTS_PER_MEGAWATT = 1.0e6

HYDRAULIC_POWER_FACTOR_MW_PER_FLOW_UNIT = (
    WATER_DENSITY_KG_PER_CUBIC_METRE
    * GRAVITATIONAL_ACCELERATION_METRES_PER_SECOND_SQUARED
    * FIXED_HYDRAULIC_HEAD_METRES
    * CUBIC_METRES_PER_FLOW_UNIT
    / (SECONDS_PER_HOUR * WATTS_PER_MEGAWATT)
)
